version: "2.2"
services:
      
  jobmanager:
    image: flink:latest
    ports:
      - "8087:8087"
    command: standalone-job --job-classname poc.learn.expert.flink.FlinkJobExecuter
    volumes:
      - ./poc-lib:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: localhost
        parallelism.default: 2        
        rest.bind-port: 8087
        
  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./poc-lib:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: localhost
        taskmanager.numberOfTaskSlots: 8
        parallelism.default: 2    
        rest.bind-port: 8087    
